### ISSUE TITLE
Neovim compatability

### ISSUE THREAD

**Issue by ranebrown** [gonzoooooo/asyncomplete-look.vim#3]
Using `v:null` instead of `v:none` also support neovim.

[These lines](https://github.com/gonzoooooo/asyncomplete-look.vim/blob/ee9540de3b6e6b1b9dc81fa7dd1505cbcaaa2e33/autoload/asyncomplete/sources/look.vim#L23-L24)

**Comment by gonzoooooo** [comment]
Thanks!
